Refactoring
coolcat-creations/plg_cccsocialmedia pull request #5
Opened 2022-03-06 16:58 UTC by nibra

### Major refactoring

* Remove avoidable dependencies
* Remove code duplication
* Use methods instead of comments
* Joomla 4 compatibility
* Remove calls to deprecated code

2022-03-14 12:26 UTC, coolcat-creations commented
Unfortunately I have still a Call to undefined method Joomla\CMS\Application\SiteApplication::getConfig() Error in J3...

2022-03-21 16:25 UTC, coolcat-creations requested changes
@nibra please check my suggestions, this should work then in J3 too (see my error from my last comment)

2022-03-21 16:25 UTC, coolcat-creations commented on plg_cccsocialmedia/cccsocialmedia.php
> +	public function onContentPrepareForm(EventInterface $event): bool
Something is wrong here and gives an Error, is the EventInterface right? Shouldn't it be Form $form or something like that?

2022-03-21 16:25 UTC, coolcat-creations commented on plg_cccsocialmedia/cccsocialmedia.php
> -		$config = Factory::getConfig();
seems to be missing as an error shows up in the frontend Call to undefined method Joomla\CMS\Application\SiteApplication::getConfig()

2022-03-21 16:25 UTC, coolcat-creations commented on plg_cccsocialmedia/cccsocialmedia.php
```suggestion
use Joomla\CMS\Factory;

```

2022-03-21 16:25 UTC, coolcat-creations commented on plg_cccsocialmedia/cccsocialmedia.php
> +		$params->set('sitename', $this->app->getConfig()->get('sitename'));
```suggestion
		$params->set('sitename', Factory::getApplication()->get('sitename'));
```

2022-03-21 16:29 UTC, coolcat-creations commented
@nibra please check my suggestions, this should work then in J3 too (see my error from my last comment)

2022-03-21 16:36 UTC, nibra commented on plg_cccsocialmedia/cccsocialmedia.php
> +	public function onContentPrepareForm(EventInterface $event): bool
I already changed that back to form with the latest commit...

2022-03-21 17:40 UTC, coolcat-creations commented on plg_cccsocialmedia/cccsocialmedia.php
> +	public function onContentPrepareForm(EventInterface $event): bool
Yes that's an old comment :) I meant my other one

2022-03-21 18:03 UTC, nibra commented
Try this- I currently have no J3 running to test it myself.

2022-03-22 09:06 UTC, merged